### ISSUE TITLE
No Sebestyen in contacts

### ISSUE THREAD

**Issue by omnosti** [jaghaimo/stelnet#105]
Hello, having an issue and I'm not sure if it's a bug or if I've missed something. I don't have Sebestyen as a contact I can call, and toggling the contactsAddSebestyen setting in the config (which started as true) doesn't seem to add him. I am playing Starsector 0.96a-RC10, and I have been using stelnet 3.0.0 on this save the entire time. I should note that I'm not done with the story yet just in case that's related, although I have 100 rep with Sebestyen and don't remember that kind of requirement in my 0.95a save.

**Comment by jaghaimo** [comment]
Thanks for the report. The way GA questline is handled internally has changed in 0.96a. Will be fixed in 3.1.0.

**Comment by jaghaimo** [comment]
Fixed in #102.
