### ISSUE TITLE
Improper icon size for intel entries

### ISSUE THREAD

**Issue by Ontheheavens** [jaghaimo/stelnet#96]
![screenshot621](https://user-images.githubusercontent.com/92992377/219855782-bb9771da-8706-46ec-a0bc-63ff2c6c3d5c.png)

**Comment by jaghaimo** [comment]
Thanks for the bug report. I will be fixing this and one more next week I hope.

Also, Discord is not letting me send you messages anymore.

**Comment by Ontheheavens** [comment]
Well, nevermind this! Fiddled for a few hours and found a satisfactory workaround - as you said, there's a way around anything, just a matter of proficiency.
![screenshot630](https://user-images.githubusercontent.com/92992377/219879879-64f14e2c-f0db-4074-a71d-630d5167a1d5.jpg)

**Comment by jaghaimo** [comment]
This was caused by vanilla not defining crest for neutral faction. Fixed on Stelnet side and reported.

**Comment by jaghaimo** [comment]
Also fixed upstream in 0.96a. This fix has now been reverted.
