### ISSUE TITLE
Add ability to transfer content between saves

### ISSUE THREAD

**Issue by jaghaimo** [jaghaimo/stelnet#98]
Possible implementation:
- dump content of player fleet (ships & items) and all storage (ships & items) to a file.
- load the content from file(s) - ships and/or items.

**Comment by stormbringer951** [comment]
Probably could be a separate mod a la old timey Save Transfer; was thinking of looking into something like this as well.

**Comment by jaghaimo** [comment]
I agree, this does not fit Stelnet. I've put it here due to the heavy `uilib` dependency, but that just means more reason to make that package a standalone lib...
